---
# 核心任务
- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common , tags: "role_common" }   
    - { role: role_countly, tags: "role_countly" }
    - { role: countly, tags: "countly" }
    - { role: role_docker, tags: "role_docker" }
    - { role: role_docker_adminmongo, tags: "role_docker_adminmongo" }
    - { role: role_init_password, tags: "role_init_password" }
    - { role: role_preend, tags: "role_preend" }
    - { role: role_end, tags: "role_end" }




    


                                                                                                    